[package]
name = "barabasi_albert_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.23", features = ["derive"] }
petgraph = "0.6.5"
petgraph-gen = "0.1.3"
rand = "0.8.5"
